zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null # Or set a list of glob patterns, e.g. ["2026/survey/**","2026/reading-group/**"]

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: https://api.siliconflow.cn/v1
  generation_kwargs:
    model: ${oc.env:OPENAI_MODEL,Qwen/Qwen2.5-7B-Instruct}
    max_tokens: 512
    temperature: 0.2
  language: English and Chinese

source:
  arxiv:
    category: ["eess.SP","cs.IT","math.IT","eess.SY","physics.app-ph"]
    include_cross_list: true

reranker:
  top_k: 5
  nearest_weight: 0.7

executor:
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv']
  max_paper_num: 20
